### ISSUE TITLE
No profiles for 'XCTestWDRunner.XCTestWDRunner.zhouzerundeMac-mini.local' were found:  Xcode couldn't find a provisioning profile matching 'XCTestWDRunner.XCTestWDRunner.zhouzerundeMac-mini.local'

### ISSUE THREAD

**Issue by HeartIsBeat** [mengdegong/iosMonkey#2]
我已经将XCTestWD的BundleId改为 XCTestWD.XCTestWD.1
XCTestWDUITests的BundleId改为 XCTestWD.XCTestWDxxx.local.1
但是跑起来，总是报：BundleId XCTestWD.XCTestWD does not exist.
![image](https://user-images.githubusercontent.com/20472976/28306521-270e731c-6bd2-11e7-81c2-e2a9f71d59d9.png)
![image](https://user-images.githubusercontent.com/20472976/28353783-d0053d44-6c8f-11e7-8fba-173108925a3e.png)
iosMonkey一直用不了。

**Comment by mengdegong** [comment]
将"XCTestWD.XCTestWD.1"改为"(唯一标识).XCTestWD"试下

**Comment by HeartIsBeat** [comment]
@mengdegong 改不了了，XCTestWD.XCTestWD 不是唯一标识。。。
![image](https://user-images.githubusercontent.com/20472976/28307739-7333a8f8-6bd6-11e7-8465-246d1c6dcc52.png)

**Comment by mengdegong** [comment]
![image](https://user-images.githubusercontent.com/25974745/28307962-519ff2b8-6bd7-11e7-8325-e427ecf0b8d4.png)
尝试一下

**Comment by HeartIsBeat** [comment]
@mengdegong 不行呀

**Comment by mengdegong** [comment]
加入QQ群:287162474,这个是配置的问题,在群里可以咨询

**Comment by HeartIsBeat** [comment]
@mengdegong macaca自动化测试，群主是谁呢，加了没给通过。

**Comment by HeartIsBeat** [comment]
@mengdegong 加群加不了；
Bundle Idxx 或 Display Name 改为 test.XCTestWD，都不行；
换个Team，都不行，Bundle Idxx就是不能为XCTestWD.XCTestWD。
T_T，求助哇！

**Comment by HeartIsBeat** [comment]
问题已解决
办法：
1.确实改为XCTestWD那个改为：wxm1.XCTestWD，XCTestWDUITest那个改为wxm1.XCTestWDUITestRunner.xxx.xxx
2.因为我换了个appid，所以app-inspector重新装下
3.重启mac和设备
4.在app-inspector能跑之后，就可以跑iosMonkey了
